version: '3.7'

volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /data/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=Asia/Seoul
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    user: "${GRA_UID}:${GRA_GID}"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - TZ=Asia/Seoul
    restart: always